name: Deploy

on: [push, pull_request]

jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Publish to NPM
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
